### PR TITLE
[11.0][IMP] account_invoice_transmit_method: use base_view_inheritance_extension

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa
Migration PR of base_view_inheritance_extension module: https://github.com/OCA/server-tools/pull/1407
Can you review that migration PR?? Thanks.

### CODE REVIEW

**Comment by jarmokortetjarvi** [comment]
This is a nice improvement for the module cross-compatibility with other modules.

You will need to add `server-tools`as OCA-dependency, though.
Like so https://github.com/OCA/sale-workflow/blob/11.0/oca_dependencies.txt
It will allow tests to run successfully.

**Comment by sergio-teruel** [comment]
@jarmokortetjarvi changes done!!

**Comment by sergio-teruel** [comment]
@jarmokortetjarvi For add oca_dependencies.txt please make a rebase from 11.0

**Comment by sergio-teruel** [comment]
@jarmokortetjarvi please, can you resolve the last comments

**Comment by jarmokortetjarvi** [comment]
@sergio-teruel the `oca_dependencies.txt` should be usable now

**Comment by rafaelbn** [comment]
Please @sergio-teruel could you please update this PR, let's see if we can merge please, thanks!

**Comment by rafaelbn** [comment]
@sergio-teruel @jarmokortetjarvi please can we fix this and merge? Please take a look! :pray:

**Comment by pedrobaeza** [comment]
@sergio-teruel I think we should close this, isn't it?

**Comment by sergio-teruel** [comment]
Now we are using https://github.com/Tecnativa/account-invoicing/tree/11.0-mig-account_invoice_transmit_method
Maybe Do I can make a new PR to a branch 11.0??

**Comment by pedrobaeza** [comment]
Yes, please, and close this one

**Comment by sergio-teruel** [comment]
I close this PR. Please see https://github.com/OCA/account-invoicing/pull/614

**Pull request closed without merging**
